name: UNC_RAx_Tutorial
channels:
- conda-forge
dependencies:
- jupyter
- scipy
- python=3.8
- scikit-learn=0.22.1
- statsmodels
- sqlalchemy
- matplotlib
- numpy
- pandas
- seaborn
- jupyterlab
- pymongo
- rdkit
- ipykernel
- pip
- pip:
  - openpyxl
  - lxml
  - --extra-index-url https://test.pypi.org/simple/
  - genra
